version: "3.9"
services:
  socks5-unauth-server:
    image: netbyte/socks5-server
    container_name: socks5-unauth-server
    ports:
      - "10080:10080"
      - "10080:10080/udp"
    command:
      - -l
      - :10080
  socks5-auth-server:
    image: netbyte/socks5-server
    container_name: socks5-auth-server
    ports:
      - "10081:10080"
      - "10081:10080/udp"
    command:
      - -l
      - :10080
      - -u
      - oshinoko
      - -p
      - hoshinoai
  ss-stream-server:
    image: ghcr.io/shadowsocks/ssserver-rust
    container_name: ss-stream-server
    ports:
      - "10090:9000"
      - "10090:9000/udp"
    volumes:
      - "./misc/ss-stream.json:/etc/shadowsocks-rust/config.json"
  ss-ahead-server:
    image: ghcr.io/shadowsocks/ssserver-rust
    container_name: ss-ahead-server
    ports:
      - "10091:9000"
      - "10091:9000/udp"
    volumes:
      - "./misc/ss-ahead.json:/etc/shadowsocks-rust/config.json"
  ss-plain-server:
    image: ghcr.io/shadowsocks/ssserver-rust
    container_name: ss-plain-server
    ports:
      - "10092:9000"
      - "10092:9000/udp"
    volumes:
      - "./misc/ss-plain.json:/etc/shadowsocks-rust/config.json"
  tuic-server:
    image: hanaasagi/tuic-server:3c7cd6
    container_name: tuic-server
    restart: always
    ports:
      - "10100:443"
      - "10100:443/udp"
    volumes:
      - ./misc/tuic-config.json:/etc/tuic/config.json:ro
      - ./misc/tuic-cert.pem:/etc/tuic/fullchain.cer:ro
      - ./misc/tuic-key.pem:/etc/tuic/private.key:ro
  vmess-server:
    image: teddysun/v2ray
    container_name: vmess-server
    ports:
      - "10110:9000"
      - "10110:9000/udp"
    volumes:
      - ./misc/vmess-config.json:/etc/v2ray/config.json:ro
