version = "Two"
unstable_features = true

condense_wildcard_suffixes = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
group_imports = "StdExternalCrate"
