[package]
name = "sazanami-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
tempfile = "3.5.0"
tracing = "0.1.38"
