name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup install stable
          rustup toolchain install nightly --component rust-src
          cargo install bpf-linker
          rustup default nightly
      - name: Setup Env
        run: docker-compose up -d
      - name: Build
        run: cargo xtask build-ebpf
      - name: Run tests
        run: cargo test --verbose
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
      - name: rust-grcov
        uses: actions-rs/grcov@v0.1.6
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          verbose: true
          fail_ci_if_error: true
